[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
headers = { "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Methods" = "GET, POST, OPTIONS", "Access-Control-Allow-Headers" = "Content-Type, Authorization" }